### ISSUE TITLE
autogen.sh fails

### ISSUE THREAD

**Issue by dodona2** [vl-nix/Helia#6] opened 2018-09-23 07:31 UTC
sh autogen.sh fails with: 'src not found'
However a directory src exists.

It fails with the recent git checkout as well with the 4.2 tar.gz archive.

**Comment by vl-nix** [comment] 2018-09-23 09:17
command: wget https://github.com/vl-nix/Helia/archive/4.2.tar.gz
 result: 4.2.tar.gz                      [           <=>                            ] 422,35K   199KB/s    за 2,1s

command: ls
 result: 4.2.tar.gz

command: tar -xvf 4.2.tar.gz && cd Helia-4.2

command: ls
 result: autogen.sh  data  LICENSE  Makefile  po  README.md  src


command: sh autogen.sh
 result:

rm -f po/*.pot po/*.po~
rm -fr build
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Copying file ABOUT-NLS
Copying file config.rpath
Copying file m4/codeset.m4
Copying file m4/extern-inline.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:13: installing './compile'
configure.ac:13: installing './config.guess'
configure.ac:13: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
Now configure process.

**Comment by dodona2** [comment] 2018-09-23 13:16
all the steps done. However again: 
rm -f po/*.pot po/*.po~
rm -fr build
autogen.sh: src: does not exist

**Comment by vl-nix** [comment] 2018-09-23 22:16
Unclear nature of the problem...
Alternatively: use make; do not use sh autogen.sh.
Download, extract, make.

**Comment by vl-nix** [comment] 2018-09-24 22:05
Operating system - Android?

**Comment by dodona2** [comment] 2018-09-24 22:13
dist: Fedora release 28 (Twenty Eight)
gcc (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)

**Comment by vl-nix** [comment] 2018-09-24 22:17
Operating System:	Ubuntu 18.04.1 LTS
gcc version 7.3.0

  helia - 4.2

  Prefix ........ :  /usr


  Gresource	 build/data/helia.gresource.c

  CC	 build/data/helia.gresource.c
  CC	 src/helia-eqa.c
  CC	 src/helia-scan.c
  CC	 src/helia-eqv.c
  CC	 src/helia-service.c
  CC	 src/helia-treeview-tv.c
  CC	 src/helia-panel-treeview.c
  CC	 src/helia-media-tv.c
  CC	 src/helia-panel-tv.c
  CC	 src/helia-gst-pl.c
  CC	 src/helia-treeview-pl.c
  CC	 src/helia-scrollwin.c
  CC	 src/main.c
  CC	 src/helia.c
  CC	 src/helia-mpegts.c
  CC	 src/helia-panel-pl.c
  CC	 src/helia-media-pl.c
  CC	 src/helia-pref.c
  CC	 src/helia-base.c
  CC	 src/helia-gst-tv.c
  CC	 src/helia-convert.c
  CCLD	 build/helia

**Comment by vl-nix** [comment] 2018-09-24 22:29
Can turn off (for test ) Gresource (icons will disappear ).
Edit Makefile:
1. configure: dirs $(desktop)
2. $(binary): $(objects)

**Comment by vl-nix** [comment] 2018-09-24 23:00
Build manually:
  gcc -Wall -Wextra src/*.c -o helia `pkg-config gtk+-3.0 --cflags --libs` `pkg-config gstreamer-video-1.0 --cflags --libs` `pkg-config gstreamer-mpegts-1.0 --libs`

**Comment by dodona2** [comment] 2018-09-25 05:31
indeed this produces a 'empty' binary (see screenshot):
https://abload.de/img/screenshotfrom2018-09f4cav.png

 gcc -Wall -Wextra src/*.c -o helia `pkg-config gtk+-3.0 --cflags --libs pkg-config gstreamer-video-1.0 --cflags --libs pkg-config gstreamer-mpegts-1.0 --libs`

**Comment by dodona2** [comment] 2018-09-25 05:37
> Can turn off ( for test ) Gresource ( icons will disappear ).
> Edit Makefile:
> 
>     1. configure: dirs $(desktop)
> 
>     2. $(binary): $(objects)
indeed this produces a 'empty' binary too (see screenshot):
https://abload.de/img/screenshotfrom2018-09f4cav.png

it creates /opt/helia/ with contents (bin  share)

**Comment by vl-nix** [comment] 2018-09-25 22:19
That's good news.

 _" 'empty' binary "_ - no, empty icons... binary ok

**Comment by vl-nix** [comment] 2018-09-25 22:43
let's try to generate gresource ( for icons )

copy text:

#!/bin/sh

# sh gen-gres.sh


GRES=helia.gresource.xml

echo "<gresources>\n<gresource prefix=\"/helia\">" > $GRES

for grfile in data/icons/*.png; do \
	echo "\t<file preprocess=\"to-pixdata\">$grfile</file>" >> $GRES; \
done

echo "</gresource>\n</gresources>" >> $GRES


glib-compile-resources $GRES --target=helia.gresource.c --generate-source

mv helia.gresource.c src/

cd src; gcc -Wall -Wextra *.c -o helia `pkg-config gtk+-3.0 --cflags --libs` `pkg-config gstreamer-video-1.0 --cflags --libs` `pkg-config gstreamer-mpegts-1.0 --libs`

to file - gen-gres.sh

run sh gen-gres.sh

**Comment by vl-nix** [comment] 2018-09-25 23:30
> build/data/helia.gresource.xml: Error on line 1 char 15: text may not appear inside .

Symbol: \\n

Thank you! The problem is fixed in the Makefile.

Update Makefile ( or clone ) and run make.

**Comment by dodona2** [comment] 2018-09-26 16:36
fix cd $1 to cd  `pwd`/$1 at line 70 of autogen.sh
I wonder, because a added pwd shows the .../trunk directory (containing src). Nevertheless only the full path works. Strange!

Finally configure fails because fedora doesn't know a gstreamer-plugins-good-devel in the repository.

**Comment by dodona2** [comment] 2018-09-26 17:07
despite configure is missing gstreamer-plugins-good-devel the 
generate manually gresource && gcc method produce a 'non empty' binary with icons playing a video without problems.

Look a this warning:
(helia:4741): Gtk-CRITICAL **: 19:01:32.190: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

**Comment by vl-nix** [comment] 2018-09-27 02:12
> only the full path

Thank you! Fixed autogen.sh.

**Comment by vl-nix** [comment] 2018-09-27 02:41
> fedora doesn't know a gstreamer-plugins-good-devel in the repository

File autogen.sh: deleted gstreamer-plugins-good-1.0

**Comment by vl-nix** [comment] 2018-09-27 04:49
> (helia:4741): Gtk-CRITICAL **: 19:01:32.190: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

File helia-scan.c modified. Function - gtk_notebook_get_tab_label - is not used.

**Comment by dodona2** [comment] 2018-09-27 08:13
**thank you very much.**
I check it out later (in the evening central european time), and report problems, if any.

**Comment by vl-nix** [comment] 2018-09-28 00:31
If possible, add a pull ( file README.md ), section Depends ( Build-Depends ) for Fedora.

**Comment by dodona2** [comment] 2018-09-28 07:07
**works fine out of the box!**
Thanks a lot! @

**Closed** 2018-09-29 00:57 UTC
